<?php
  include 'include/config.php';
  include 'include/header.html';
?>

  <h1>Hello world from PHP</h1>
  <p>You can remix this project for a plain PHP starter. Some database is configured (see sample.sql), but none of the MVC framwork is here. You can write code directly in this file.</p>
    
<?php
  echo "<ul>";
  for ($i = 0; $i < 10; ++$i) {
    echo "  <li> Generated by code, line $i </li>";
  }
  echo "</ul>";
?>
    
<?php
  include 'include/footer.html';
?>